# Generated by Django 5.0.2 on 2024-02-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_cpf_alter_client_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.CharField(max_length=9),
        ),
    ]
